version: "3.8"

volumes:
  postgres-data: {}

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=nigger
      - POSTGRES_PASSWORD=Password&12345678
    volumes:
      - postgres-data:/var/lib/postgresql/data/