version: "3.8"

volumes:
  mongodb-data: {}

services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${GLOBAL_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${GLOBAL_PASSWORD}
    volumes:
      - mongodb-data:/data/db
