version: "3.8"

volumes:
  mssql-data: {}

services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    ports:
      - "1434:1433"
    environment:
      - SA_PASSWORD=Password&12345678
      - ACCEPT_EULA=Y
    volumes:
      - mssql-data:/var/opt/mssql