version: "3.8"

volumes:
  seq-data: {}

services:
  seq:
    container_name: seq
    image: datalust/seq
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq-data:/data