version: "3.8"

volumes:
  redisinsight-data: {}

services:
  redisinsight:
    container_name: redisinsight
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    volumes:
      - redisinsight-data:/data